### ISSUE TITLE
No tokens left for this setting. Consider raising prob_limit=-15

### ISSUE THREAD

**Issue by m3xw3ll** [RasaHQ/whatlies#101]
I am following the instruction on youtube to reproduce the word embeddings. 

Here is the code:

```
from whatlies import Embedding, EmbeddingSet
from whatlies.language import SpacyLanguage
lang_spacy = SpacyLanguage("en_core_web_md")
lang_spacy.score_similar('university')
```

I´ll get following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-9705af8b0442> in <module>
----> 1 lang_spacy.score_similar('university')

~\Anaconda3\envs\nlpenv\lib\site-packages\whatlies\language\spacy_lang.py in score_similar(self, emb, n, prob_limit, lower, metric)
    222             emb = self[emb]
    223 
--> 224         queries = self._prepare_queries(prob_limit, lower)
    225         distances = self._calculate_distances(emb, queries, metric)
    226         by_similarity = sorted(zip(queries, distances), key=lambda z: z[1])

~\Anaconda3\envs\nlpenv\lib\site-packages\whatlies\language\spacy_lang.py in _prepare_queries(self, prob_limit, lower)
    134             queries = [w for w in queries if w.is_lower]
    135         if len(queries) == 0:
--> 136             raise ValueError(
    137                 f"No tokens left for this setting. Consider raising prob_limit={prob_limit}"
    138             )

ValueError: No tokens left for this setting. Consider raising prob_limit=-15
```

If i change the prob_limit to -15 I get the same error message. 
If I modify the last line of code into` lang_spacy.score_similar('university', prob_limit=None)` the code works but I get following results:

```
[(Emb[university], 5.960464477539063e-08),
 (Emb[where], 0.6037042140960693),
 (Emb[who], 0.6461576223373413),
 (Emb[there], 0.6536556482315063),
 (Emb[he], 0.6619330644607544),
 (Emb[she], 0.6653806567192078),
 (Emb[must], 0.6659252047538757),
 (Emb[should], 0.6668630838394165),
 (Emb[how], 0.6717931032180786),
 (Emb[what], 0.6724168062210083)]
```

But this can´t be right or? I don´t want subwords. 

Any suggestions what I am doing wrong?

spacy version 2.3.2
whatlies version 0.4.2

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
That's strange. These are my results. 

<img width="644" alt="image" src="https://user-images.githubusercontent.com/1019791/89436360-6a572500-d746-11ea-8703-820c603da69c.png">

Are you use you're running `en_core_web_md` and not `en_core_web_sm`?

**Comment by m3xw3ll** [comment]
> That's strange. These are my results.
> 
> <img alt="image" width="644" src="https://user-images.githubusercontent.com/1019791/89436360-6a572500-d746-11ea-8703-820c603da69c.png">
> 
> Are you use you're running `en_core_web_md` and not `en_core_web_sm`?

I used the German spaCy-Modell, but I just tried the English one as well. I get the same error. 

![image](https://user-images.githubusercontent.com/45366523/89507524-e85e0f00-d7cc-11ea-8d9a-0149d4fd2c64.png)

**Comment by koaning** [comment]
What do you see when you run; 

```python
> len(lang_spacy.model.vocab)
# 1340241
> lang_spacy.model.vocab['university']
# lang_spacy.model.vocab['university']
```

**Comment by m3xw3ll** [comment]
hm, I think thats the problem. 

```
len(lang_spacy.model.vocab)
# 491
lang_spacy.model.vocab['university']
# <spacy.lexeme.Lexeme at 0x1ccd35b3300>
```

**Comment by koaning** [comment]
Something is telling me that somehow you've gotten a strange spaCy model. You can try re-downloading. I think spaCy 3.0 is due soon-ish so there might be something on that side that's happening. 

Let me know!

**Comment by m3xw3ll** [comment]
Just reinstalled the spaCy model, same problem. I try to set up a fresh environement and try it again. 
I will let you know if that solved the problem.

**Comment by mkaze** [comment]
I can reproduce the issue with whatlies 0.4.5 and spacy 2.3.2.
@koaning What version of these are you using? And what version of the model (i.e. use `pip show en-core-web-md`)?

**Comment by koaning** [comment]
Hey you're right.

```python
spacy==2.2.4
en-core-web-lg==2.2.5
en-core-web-md==2.2.5
en-core-web-sm==2.2.5
```

I'll see if I've got time today to investigate some more. It seems like spaCy made a breaking change that I wasn't aware of.

**Comment by koaning** [comment]
Yeah they seem to have added [a big change](https://spacy.io/usage/v2-3).

<img width="819" alt="image" src="https://user-images.githubusercontent.com/1019791/89618125-d1322680-d88b-11ea-98aa-4f216ac551fb.png">

Should be relatively easy to fix. What I'm more worried about is how to properly test this. We might need to seriously start thinking about model caching.

**Comment by koaning** [comment]
I also think that it starts making sense to have a page on the documentation that mentions which version numbers are supported in which version of whatlies.

**Comment by mkaze** [comment]
@koaning Yeah, that's exactly what I was referring to. It's a backwards incompatible change. And also another one: the `prob` values are not loaded since version 2.3. Instead, another package, i.e. `spacy-lookups-data`, should be installed as well so that they could be loaded.

> What I'm more worried about is how to properly test this. We might need to seriously start thinking about model caching.

Yeah, that's why I argued in favor of testing on real use-cases and models as well.

> I also think that it starts making sense to have a page on the documentation that mentions which version numbers are supported in which version of whatlies.

Yeah, that might be a good thing to make the user being aware of.

**Comment by mkaze** [comment]
@koaning One more point: the spacy models are hosted on Github [as releases of a repository](https://github.com/explosion/spacy-models/releases); so if [your concern](https://github.com/RasaHQ/whatlies/pull/103#issuecomment-667983494) about using the models in the tests is just the costs of hosting for spaCy maintaiers, then I don't think that would be an issue (i.e. I don't think there is any cost associated with downloading from a repository releases). So they could be used even without caching, and also since they are hosted on Github the download time would be probably very short in Github Actions.

BTW, are you working on a PR for this issue?

**Comment by koaning** [comment]
Not yet. I tend to work on whatlies sporadically during Rasa office hours. Today is a day off so I'll work on this on monday. Feel free to pick it up.

Also, just to check @mkaze I've noticed you've been picking up a lot of tickets/PRs. Is there any particular reason you're so invested in this project? You use this project yourself?

**Comment by mkaze** [comment]
@koaning 
> I've noticed you've been picking up a lot of tickets/PRs. Is there any particular reason you're so invested in this project?

I laughed when I read this sentence, because it's not clear from it if you are happy about them or not :smile: But since you are curios, let me explain:

No, I don't use `whatlies` in any serious project/research (yet!). Actually, I don't have much public open-source contributions as well; I used to contribute to Keras and its sister projects almost two years ago (e.g. [this PR](https://github.com/keras-team/keras/pull/11808)), however I became a bit disappointed since the review process was very slow back then and also there were rumors that it would be finally merged with TF (which happened finally!). I became occupied with my daily job and only continued [contributing to Stack Overflow](https://stackoverflow.com/users/2099607/today?tab=profile) from time to time. 

But since the past few months I was again looking for a good open-source project at early-stage to contribute to. I have a good friend (who is also a former colleague of mine, and I think knows you as well) with whom we exchange problems or QAs or ideas about ML/NLP from time to time. Almost one month ago, he showed me "whatlies" project and a week later talked about you and other projects you are working on. So I looked at this project and become interested to contribute to it, because: 1) it was at early stage yet, 2) it was about ML/NLP which is my working domain, 3) in a way, it could be sub-categorized under "model interpretability" domain as well which I think is very important and insightful..... and you know the rest of the story.... :smile:

**Comment by koaning** [comment]
@mkaze this was mainly a question out of curiosity actually 😄. To be clear: I'm really happy with the contributions you've made! It's just that I maintain quite a few projects and it just struck me that your activity certainly is above average.

I share your experience with big open source projects. Open source projects can get really bureaucratic once they're big. I recall a collegue who had a PySpark PR that got merged *after five years*. It's also my preference to keep it smaller where possible. 

I agree that model interpretability is indeed a worthy domain. It's funny it wasn't the goal initially of this library. My initial goal was to write a library to help me explain word embeddings better. Sofar, the more I'm able to visualise the embeddings the more I recognize how much hype there has been on the topic. King - Man + Woman = King (not queen). 

Some members of our research team also like it to explore new embeddings with this library but it's safe to say there's more users outside of Rasa now than inside.
