### ISSUE TITLE
Using "setup.py develop" in makefile

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#64]
I was wondering why the `python setup.py develop` has been used in `develop` target of makefile, especially when editable installation mode of `pip` have been used as well (i.e. `pip install -e` and `pip install -e .[dev]`). As far as I know, this not only makes it redundant, but also using `setup.py` is not recommended due to its potential conflicting behavior. Maybe it's there for good reasons which I am not aware of and would like to know.

If this is indeed a mistake, I can push a fix as a PR if you would like.

**Comment by koaning** [comment]
This feels like an issue that I wouldn't notice because I've already installed everything locally. It makes sense that somebody else discovers this while setting up. Feel free to remove "python setup.py develop" in favor of "pip install e .[dev]".

I may suggest one thing. I think this may be the safest.

```
python -m pip install -e ".[dev]"
```

The `python -m pip` makes it 100% sure we install in the correct venv and `".[dev]"` ensures that the install also works on zsh.
